### ISSUE TITLE
DCS foveated rendering doesn't seem to work

### ISSUE THREAD

**Issue by akhamar** [fholger/vrperfkit#19] opened 2022-01-21 19:57 UTC
I got the following in log file while applying foveated rendering.
```
(DEBUG) VRS: Single eye target, don't know which eye (multiple lines)
```

The config file is the following :
```
upscaling:
  enabled: true
  method: nis
  renderScale: 0.59
  sharpness: 0.6
  radius: 0.6
  applyMipBias: true
fixedFoveated:
  enabled: true
  innerRadius: 0.2
  midRadius: 0.4
  outerRadius: 0.6
debugMode: true
hotkeys:
  enabled: true
  toggleDebugMode: ["ctrl", "shift", "f1"]
  cycleUpscalingMethod: ["ctrl", "shift", "f2"]
  increaseUpscalingRadius: ["ctrl", "shift", "f3"]
  decreaseUpscalingRadius: ["ctrl", "shift", "f4"]
  increaseUpscalingSharpness: ["ctrl", "shift", "f5"]
  decreaseUpscalingSharpness: ["ctrl", "shift", "f6"]
  toggleUpscalingApplyMipBias: ["ctrl", "shift", "f7"]
  captureOutput: ["ctrl", "shift", "f8"]
  toggleFixedFoveated: ["alt", "shift", "f1"]

```

Full log :
```
20:43:01 [17616] Current configuration:
20:43:01 [17616]   Upscaling (NIS) is enabled
20:43:01 [17616]     * Render scale: 0.59
20:43:01 [17616]     * Sharpness:    0.6
20:43:01 [17616]     * Radius:       0.6
20:43:01 [17616]     * MIP bias:     enabled
20:43:01 [17616]   Debug mode is enabled
20:43:01 [17616] Currently active hotkeys:
20:43:01 [17616]   * cycleUpscalingMethod 17 16 113
20:43:01 [17616]   * increaseUpscalingRadius 17 16 114
20:43:01 [17616]   * decreaseUpscalingRadius 17 16 115
20:43:01 [17616]   * increaseUpscalingSharpness 17 16 116
20:43:01 [17616]   * decreaseUpscalingSharpness 17 16 117
20:43:01 [17616]   * toggleDebugMode 17 16 112
20:43:01 [17616]   * toggleUpscalingApplyMipBias 17 16 118
20:43:01 [17616]   * toggleFixedFoveated 18 16 112
20:43:01 [17616]   * captureOutput 17 16 119
20:43:01 [17616] Installing hook for LoadLibraryA from 00007FF85B6404F0 to 00007FFFC255B2C0
20:43:01 [17616] Installing hook for LoadLibraryExA from 00007FF85B63FBC0 to 00007FFFC255B310
20:43:01 [17616] Installing hook for LoadLibraryW from 00007FF85B63FEE0 to 00007FFFC255B3F0
20:43:01 [17616] Installing hook for LoadLibraryExW from 00007FF85B63ADC0 to 00007FFFC255B380
20:43:01 [17616] d3d11.dll is loaded in the process, installing hooks...
20:43:01 [17616] Installing hook for D3D11CreateDevice from 00007FF854CBFCB0 to 00007FFFC253CBA0
20:43:01 [17616] Installing hook for D3D11CreateDeviceAndSwapChain from 00007FF854CBFE20 to 00007FFFC253D020
20:43:16 [17616] vrclient_x64.dll is loaded in the process, installing hooks...
20:43:16 [17616] Installing hook for VRClientCoreFactory from 00007FFFEA4C2AF0 to 00007FFFC25448B0
20:43:16 [17616] OpenVR: requested interface IVRClientCore_003
20:43:16 [17616] Installing virtual function hook for IVRClientCore::GetGenericInterface
20:43:16 [17616] Installing virtual function hook for IVRClientCore::Cleanup
20:43:16 [17616] OpenVR: requested interface IVRClientCore_003
20:43:16 [17616] Removing hook to 00007FFFEA4B9200
20:43:16 [17616] Removing hook to 00007FFFEA4BA800
20:43:16 [17616] Installing virtual function hook for IVRClientCore::GetGenericInterface
20:43:16 [17616] Installing virtual function hook for IVRClientCore::Cleanup
20:43:16 [17616] OpenVR: requested interface IVRRenderModels_006
20:43:16 [17616] OpenVR: requested interface IVRRenderModelsInternal_XXX
20:43:16 [17616] OpenVR: requested interface IVRResources_001
20:43:16 [17616] OpenVR: requested interface IVRDriverManager_001
20:43:16 [17616] OpenVR: requested interface IVRSettings_003
20:43:16 [17616] OpenVR: requested interface IVRSettingsInternal_001
20:43:16 [17616] OpenVR: requested interface IVRPaths_001
20:43:16 [17616] OpenVR: requested interface IVRPathsInternal_001
20:43:16 [17616] OpenVR: requested interface IVRProperties_001
20:43:16 [17616] OpenVR: requested interface IVRPropertiesInternal_001
20:43:16 [17616] OpenVR: requested interface IVRServer_XXX
20:43:16 [17616] OpenVR: requested interface IVRSystemLayerInternal_XXX
20:43:16 [17616] OpenVR: requested interface IVRClientInternal_XXX
20:43:16 [17616] OpenVR: requested interface LocalizationManager
20:43:16 [17616] OpenVR: requested interface IVRCompositorSystemInternal_001
20:43:16 [17616] OpenVR: requested interface IVRInput_010
20:43:16 [17616] OpenVR: requested interface IVRInputInternal_002
20:43:16 [17616] OpenVR: requested interface IVRChaperone_004
20:43:16 [17616] OpenVR: requested interface IVRChaperoneSetup_006
20:43:16 [17616] OpenVR: requested interface IVRChaperoneInternal_001
20:43:16 [17616] OpenVR: requested interface IVRApplications_007
20:43:16 [17616] OpenVR: requested interface IVRSystem_022
20:43:16 [17616] Installing virtual function hook for IVRSystem::GetRecommendedRenderTargetSize
20:43:16 [17616] OpenVR: requested interface IVRMailbox_002
20:43:16 [17616] OpenVR: requested interface IVRDebug_001
20:43:16 [17616] OpenVR: requested interface IVRBlockQueue_004
20:43:16 [17616] OpenVR: requested interface IVRControlPanel_006
20:43:16 [17616] OpenVR: requested interface IVRApplicationsInternal_XXX
20:43:16 [17616] OpenVR: requested interface IVRResources_001
20:43:16 [17616] OpenVR: requested interface IVRDriverDirectInternal_XXX
20:43:16 [17616] OpenVR: requested interface IVROverlay_025
20:43:16 [17616] OpenVR: requested interface IVROverlayInternal_XXX
20:43:16 [17616] OpenVR: requested interface IVRDriverDirectInternal_XXX
20:43:16 [17616] OpenVR: requested interface IVRExtendedDisplay_001
20:43:16 [17616] OpenVR: requested interface IVRTrackedCameraInternal_XXX
20:43:16 [17616] OpenVR: requested interface IVRCompositor_027
20:43:16 [17616] Installing virtual function hook for IVRCompositor::WaitGetPoses
20:43:16 [17616] Installing virtual function hook for IVRCompositor::PostPresentHandoff
20:43:16 [17616] Installing virtual function hook for IVRCompositor::Submit
20:43:16 [17616] OpenVR: requested interface IVRSystem_019
20:43:16 [17616] OpenVR: requested interface IVRCompositor_022
20:43:16 [17616] OpenVR: requested interface IVRExtendedDisplay_001
20:43:16 [17616] OpenVR: requested interface IVRRenderModels_006
20:43:16 [17616] (DEBUG) Redirecting D3D11CreateDevice to system
20:43:16 [17616] (DEBUG) Redirecting D3D11CreateDeviceAndSwapChain to system
20:43:16 [17616] Loading DLL at "C:\\WINDOWS\\system32\\dxgi.dll"
20:43:16 [17616] (DEBUG) Redirecting CreateDXGIFactory2 to system
20:43:21 [17616] Game is submitting D3D11 textures, creating necessary output resources...
20:43:21 [17616] Trying to load NVAPI...
20:43:21 [17616] Successfully initialized NVAPI; Variable Rate Shading is available.
20:43:21 [17616] Installing virtual function hook for ID3D11DeviceContext::PSSetSamplers
20:43:21 [17616] Installing virtual function hook for ID3D11DeviceContext::OMSetRenderTargets
20:43:21 [17616] Installing virtual function hook for ID3D11DeviceContext::OMSetRenderTargetsAndUnorderedAccessViews
20:43:21 [17616] (DEBUG) Create UAV for texture of format 28 and view dimension 4
20:43:21 [17616] OpenVR: requested interface IVRSystem_022
20:43:21 [17616] Raw projection for eye 0: l -1.5, r 1.1, t -1.4, b 1.4
20:43:21 [17616] Display is canted by 0 RAD
20:43:21 [17616] Projection center for eye 0: 0.59, 0.5
20:43:21 [17616] Raw projection for eye 1: l -1.1, r 1.5, t -1.4, b 1.4
20:43:21 [17616] Display is canted by -0 RAD
20:43:21 [17616] Projection center for eye 1: 0.41, 0.5
20:43:21 [17616] OpenVR: requested interface IVRSystem_022
20:43:21 [17616] Creating shader resource view for input texture 000001FFD3881D78
20:43:21 [17616] Creating D3D11 resources for NIS upscaling...
20:43:21 [17616] (DEBUG) MIP LOD Bias changed from 0 to -0.76, recreating samplers
20:43:21 [17616] OpenVR: requested interface IVRSettings_003
20:43:21 [17616] OpenVR: requested interface IVRResources_001
20:43:21 [17616] OpenVR: requested interface IVRCompositorSystemInternal_001
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] Creating replacement sampler for 0000020057E47EE0 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A8CA0 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970AA320 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970AA8E0 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A7760 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A6420 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A7620 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A7520 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A61E0 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A60E0 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A5FA0 with MIP LOD bias -0.76
20:43:21 [17616] Creating replacement sampler for 000001FF970A5EA0 with MIP LOD bias -0.76
20:43:21 [17616] Creating shader resource view for input texture 000001FFD3882A78
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] Creating replacement sampler for 0000020057E446A0 with MIP LOD bias -0.76
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] Creating replacement sampler for 000001FF970A9B60 with MIP LOD bias -0.76
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:21 [17616] (DEBUG) VRS: Single eye target, don't know which eye
...
20:43:56 [17616] Fixed foveated is now disabled
20:43:57 [17616] Average GPU processing time for post-processing: 0.48 ms
20:43:57 [17616] Fixed foveated is now enabled
20:43:57 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:57 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:43:57 [17616] (DEBUG) VRS: Single eye target, don't know which eye
20:44:00 [17616] Fixed foveated is now disabled
...
```

So each time I activate the foveated rendering it seem it goes fubar with the debug log `(DEBUG) VRS: Single eye target, don't know which eye`

**Comment by akhamar** [comment] 2022-01-21 20:02
From what I understand, the code for foveated rendering is not done yet, correct ?

**Comment by lv426hudson** [comment] 2022-01-22 09:43
> 

But it says this in version 0.2 of the mod? Its a bit confusing that it states it has and and also that its planned?

Added fixed foveated rendering via Variable Rate Shading (only available for NVIDIA RTX and GTX 16xx cards)

**Comment by mhjmaas** [comment] 2022-01-22 09:51
I believe VRSS works only for forward rendering pipelines. DCS used a deferred rendering pipeline. Maybe the planned addition of rendering less pixels will work.

**Comment by fholger** [comment] 2022-01-22 11:17
VRS is implemented, and it does work for deferred pipelines, just not for certain kinds of games. To properly apply VRS, I need to match the VRS pattern to the rendered eye. Most games/engines render to a combined or array texture, where it is clear which portion of the texture corresponds to each eye. However, some games like DCS render the eyes to separate textures, and unfortunately there is no clear way to know when it is rendering which eye. Therefore VRS is currently not active for these games.

**Comment by Sirtz** [comment] 2022-01-22 13:30
vrperfkit is already giving fantastic results in DCS, if there would be a way in the future to make VRS work the community would be forever thankful. I literally went from a fluctuating 35fps to stable 45 fps using this mod, which absolutely fantastic, and sorely needed since eagle dynamics doesn't seem to care about VR optimisation.

**Comment by cedriclmenard** [comment] 2022-01-22 17:56
I'm currently investigating making a dedicated fork of your repo for DCS. I'll report the results, but so far I've been able to identify the correct framebuffers for each eye using RenderDoc.

**Comment by Zorinco96** [comment] 2022-01-22 17:57
Keep me updated! I'd love to help with that however I can.

**Comment by lv426hudson** [comment] 2022-01-22 18:03
> vrperfkit is already giving fantastic results in DCS, if there would be a way in the future to make VRS work, the community would be forever thankful. I literally went from a fluctuating 35fps to stable 45 fps using this mod, which absolutely fantastic, and sorely needed since eagle dynamics doesn't seem to care about VR optimisation.

The boost this is giving you will be purely from the fsr upscaling at the moment? Until ffr is implemented?

**Comment by Sirtz** [comment] 2022-01-23 00:36
> The boost this is giving you will be purely from the fsr upscaling at the moment? Until ffr is implemented?

Yes I think so, although I have better fps with vrperfkit than before just using fsr mod for some reason. Unscientific observation.

**Comment by cedriclmenard** [comment] 2022-01-23 01:25
I might have found a very hacky workaround, because the eye render target views are always processed in the same order (left then right). I need to test it more thoroughly but I'll update this thread issue when I get more testing done.

**Comment by akhamar** [comment] 2022-01-23 01:37
Could be a good idea to add a param, under FFR, to choose which eyes is processed. Like that we could activate for deferred rendering based on try and error.

```
fixedFoveated:
  enabled: true/false
  innerRadius: 0.0-1.0
  midRadius: 0.0-1.0
  outerRadius: 0.0-1.0
  deferredBypass:
    enabled: true/false
    eyeRenderingOrder: ["left", "right"]
    or
    leftEyeRenderingFirst: true/false
```

**Comment by fholger** [comment] 2022-01-23 06:38
It isn't just the order; the order is almost always left eye first. I can't remember a single game that renders the right eye first. However, what varies drastically is how many render passes are involved and how many render targets are used for each eye, especially in deferred pipelines.

**Comment by flasheeprom** [comment] 2022-01-23 12:05
If you find a solution to get FFR working in DCS, it would be nice to add support for AMDs VSR so we can have FFR working on AMD cards as well.

**Comment by fholger** [comment] 2022-01-23 12:13
That's impossible. AMD does not have support for VRS in DX11, only in DX12 or Vulkan. The only way that could be made to work in an existing game would be by using dxvk as a DX11 to Vulkan translation layer. And while I have been able to make that work, in principle, it does not currently work well. It would cost you more in performance than you'd gain.

**Comment by cedriclmenard** [comment] 2022-01-23 22:45
So, as @fholger said, there's no way by intercepting `OMSetRenderTarget` to actually know which eye is which, even by filtering by texture properties. What seems to happen though is that the Nvidia's VRS implementation propagate to both eye's render targets and thus VRS does work, BUT.

And this is a big BUT, it has several drawbacks, namely:
- It breaks UI texts, as they get through the VRS "pipeline" and therefore the further away from the render target center the text is, the more unreadable/blurry it gets.
- I must apply a purely centered VRS pattern, not centered on the projective center of the eye viewport. At higher radii like the default values are set (0.6 and 0.8), this is fine and it doesn't really show any drawbacks, but at more performance oriented radii, some artifacts appear when looking towards your nose.

I'm honestly not sure this is even worth publishing, as these are pretty big caveats.

**Comment by Sirtz** [comment] 2022-01-23 23:23
Sure, publish it! Why not, I would love to try it. Also would enable future work or reference on it :)

**Comment by Zorinco96** [comment] 2022-01-24 00:19
Absolutely publish that, since those drawbacks would be acceptable with some programs. I'd use it for DCS, and if the UI is screwed up, then oh well... I don't care much, but if I can use VRS with FSR that means I can get a better center at acceptable performance, especially with higher rez headsets like the Pimax

**Comment by cedriclmenard** [comment] 2022-01-24 02:29
Alright I've managed to "fix" the UI text rendering issue. Now the only real big issue is the foveated rendering center, but in my testing it works quite well.

See this release: https://github.com/cedriclmenard/vrperfkit/releases/tag/v0.2.2-dcs-ffr

Disclaimer: this was only tested by me on a single computer.

**Comment by akhamar** [comment] 2022-01-24 03:37
I've just tryed it. Seem to be "working" on valve index.
But indeed the center of VRS is not at center but with on offset on the right (right eye) and on the left (left eye).
Also sadly you can't see aera of effect like with upscaling with a colored circle to double check it's working or not.

toggleDebugMode show circle for upscaling but not for VRS, maybe it's already missing from the original vrperfkit ?

**Comment by Zorinco96** [comment] 2022-01-24 07:33
> Alright I've managed to "fix" the UI text rendering issue. Now the only real big issue is the foveated rendering center, but in my testing it works quite well.
> 
> See this release: https://github.com/cedriclmenard/vrperfkit/releases/tag/v0.2.2-dcs-ffr
> 
> Disclaimer: this was only tested by me on a single computer.

Just tested it for a bit tonight on my PC running a Pimax headset. Good results with the VRS at least with my setup. I have the radii set to 0.45 / 0.7 / 0.71, along with a FSR of 0.75 with Steam at 200%. The use of the VRS allowed me to push up the Steam resolution quite a bit with the extra GPU headroom.

**Comment by fholger** [comment] 2022-01-24 07:57
> I've just tried it. It seem to be "working" on valve index. But indeed the center of VRS is not at center but with on offset on the right (right eye) and on the left (left eye). Also sadly you can't see area of effect like with upscaling with a colored circle to double check it's working or not.
> 
> toggleDebugMode show circle for upscaling but not for VRS, maybe it's already missing from the original vrperfkit ?

Yes, that's missing even in vrperfkit base. The reason is that for VRS there is no straight-forward way to show that. I would have to add a separate render pass, and the circles I draw in that separate pass could theoretically end up completely different from the actual VRS pattern due to bugs etc.. So I think it isn't really worth it.
Instead, monitor your GPU frame time. If it isn't changing when toggling VRS on and off, then it's either not working or has no benefit for the game.

**Comment by akhamar** [comment] 2022-01-24 09:47
> > I've just tried it. It seem to be "working" on valve index. But indeed the center of VRS is not at center but with on offset on the right (right eye) and on the left (left eye). Also sadly you can't see area of effect like with upscaling with a colored circle to double check it's working or not.
> > toggleDebugMode show circle for upscaling but not for VRS, maybe it's already missing from the original vrperfkit ?
> 
> Yes, that's missing even in vrperfkit base. The reason is that for VRS there is no straight-forward way to show that. I would have to add a separate render pass, and the circles I draw in that separate pass could theoretically end up completely different from the actual VRS pattern due to bugs etc.. So I think it isn't really worth it. Instead, monitor your GPU frame time. If it isn't changing when toggling VRS on and off, then it's either not working or has no benefit for the game.

Yep agree.
I've tried multiple config of VRS on DCS with the workaround of @cedriclmenard. It give me +10% on not complex scene and only 1-3% on heavy loaded scene.
Sadly it doesn't give much more than up-scaling.

So VRS alone is not enough. I'll try to combine it with NIS or FSR and see what result it give.

**Comment by cedriclmenard** [comment] 2022-01-24 11:16
To test if it actually works, simply use very small radius values. You’ll instantly see the pixelation if it does work.

**Comment by cedriclmenard** [comment] 2022-01-24 11:18
> > > I've just tried it. It seem to be "working" on valve index. But indeed the center of VRS is not at center but with on offset on the right (right eye) and on the left (left eye). Also sadly you can't see area of effect like with upscaling with a colored circle to double check it's working or not.
> > > toggleDebugMode show circle for upscaling but not for VRS, maybe it's already missing from the original vrperfkit ?
> > 
> > 
> > Yes, that's missing even in vrperfkit base. The reason is that for VRS there is no straight-forward way to show that. I would have to add a separate render pass, and the circles I draw in that separate pass could theoretically end up completely different from the actual VRS pattern due to bugs etc.. So I think it isn't really worth it. Instead, monitor your GPU frame time. If it isn't changing when toggling VRS on and off, then it's either not working or has no benefit for the game.
> 
> Yep agree. I've tried multiple config of VRS on DCS with the workaround of @cedriclmenard. It give me +10% on not complex scene and only 1-3% on heavy loaded scene. Sadly it doesn't give much more than up-scaling.
> 
> So VRS alone is not enough. I'll try to combine it with NIS or FSR and see what result it give.

Unfortunately I think this arises at least a bit from the fact that DCS doesn’t seem to use fostrum culling in VR. There’s an option to turn it on in a lua file, but it breaks several things in DCS.

**Comment by flasheeprom** [comment] 2022-01-24 11:39
> Unfortunately I think this arises at least a bit from the fact that DCS doesn’t seem to use fostrum culling in VR. There’s an option to turn it on in a lua file, but it breaks several things in DCS.

What? They don't do Frustum Culling? I can understand that if you want to keep objects behind you that cast a shadows into your active frustum. I even remember seeing this effect (shadows vanishing when turning my head with TrackIR). I haven't payed attention to see if this is true in VR though.

**Comment by cedriclmenard** [comment] 2022-01-24 12:49
AFAIK, nope. The option described in the following link uses it, but it breaks the in-cockpit lighting and several other things.

https://forums.eagle.ru/topic/230316-wipstereo_mode_use_shared_parser-helps-a-lot-with-balancing-cpugpu-usage/

**Comment by akhamar** [comment] 2022-01-24 14:54
Sometimes I hate so much ED for doing a crappy job with their 20 years old 3D engine and not realizing they need to redo it.

**Comment by akhamar** [comment] 2022-01-24 17:34
@cedriclmenard game crash if I activate FFT and upscaling (nis and fsr)

**Comment by Sirtz** [comment] 2022-01-24 17:36
@cedriclmenard tried it today, works really well, thanks a ton!

**Comment by Sirtz** [comment] 2022-01-24 18:51
yes, no crashes here.

**Comment by akhamar** [comment] 2022-01-24 18:55
Weird ... Can you try F/A-18C, caucasian, dark and cold ?

**Comment by akhamar** [comment] 2022-01-24 18:59
Also can you share the config file you are using (excluding the # comment) ?

**Comment by Sirtz** [comment] 2022-01-25 15:04
> Weird ... Can you try F/A-18C, caucasian, dark and cold ?

![image](https://user-images.githubusercontent.com/26656736/151001695-4950829b-4d8f-4210-8ef3-f5a9e27be245.png)
[vrperfkit.yml.txt](https://github.com/fholger/vrperfkit/files/7934622/vrperfkit.yml.txt)

**Comment by DJSlane** [comment] 2022-01-26 00:29
I am confused regarding the difference between VRS and FFR.  Can you get one without the other? I guess I love DCS so much I was hoping to at least see one of the options at work. Thanks for any feedback you can offer. I tried the modified dxgi and I found it just killed the resolution overall. I do appreciate your efforts in this area as DCS is literally the pinnacle of the need for Wide FOV and high clarity.

**Comment by cedriclmenard** [comment] 2022-01-26 23:43
> I tried and it seemed to succeed according to the log, but no hotkeys seemed to affect the output at all. The debug didn't mask the screen and nothing seemed to affect the output or fps at all, suggesting it's not hooking or something. I am using a Pimax 8KX if that helps at all.

The debug option doesn't work for foveated rendering, as @fholger has already explained.

Try a low inner radius value (like 0.1) and you'll see a ton of pixelation indicating that it does indeed work.

**Comment by DJSlane** [comment] 2022-01-27 03:41
Ok ill give it a new go this evening. So it disables the debug mask, or the entire debug mode? Sorry I read up and couldn't discern.

**Comment by pahi** [comment] 2022-01-29 22:58
> Alright I've managed to "fix" the UI text rendering issue. Now the only real big issue is the foveated rendering center, but in my testing it works quite well.
> 
> See this release: https://github.com/cedriclmenard/vrperfkit/releases/tag/v0.2.2-dcs-ffr
> 
> Disclaimer: this was only tested by me on a single computer.

This works fine on my PC with the Valve Index & ootb settings.

**Comment by Sirtz** [comment] 2022-01-30 13:18
Been using @cedriclmenard fix for a week now, and it works really well. Maybe merge it? The fork is kind of confusing tbh.

**Comment by akhamar** [comment] 2022-01-30 15:25
> > Alright I've managed to "fix" the UI text rendering issue. Now the only real big issue is the foveated rendering center, but in my testing it works quite well.
> > See this release: https://github.com/cedriclmenard/vrperfkit/releases/tag/v0.2.2-dcs-ffr
> > Disclaimer: this was only tested by me on a single computer.
> 
> This works fine on my PC with the Valve Index & ootb settings.

If I activate at both time FFR and scaling the game crash on me after 10-30sec.

**Comment by Zorinco96** [comment] 2022-01-30 18:12
If you were using the older VR for FSR mod, be sure that you've uninstalled that and restored the old files. And if running reshade be sure to rename tge dxgi.dll

**Comment by akhamar** [comment] 2022-01-30 20:51
> If you were using the older VR for FSR mod, be sure that you've uninstalled that and restored the old files. And if running reshade be sure to rename tge dxgi.dll

All have been removed

**Comment by DJSlane** [comment] 2022-01-31 18:51
Yeah I tried it once more. It is because I'm using a Pimax as I suspected. The foveated position is in the center of each image, whereas the FSR render radius is correct and places them properly offset. So, when using non-parallel projection (DCS being one of the few wonderful games that fully supports that) -causes the sweet spot to be to the left in the left eye, right in the right eye. I'd love to see an update where the offset is somehow copied from the FSR/NIS/CAS radius as that works wonderfully! I also noted that FFR doesn't increase the frame rate as much as I thought it would (I'm not CPU bound at all). Even on a 3090 it seems similar as to full resolution. I'm not griping about the mod at all, just can't figure out why rendering at 1/16th resolution over much of the screen somehow still costs so much. Is it related to the render pipeline perhaps? Thank you for your work on this mod! Perhaps fholger can share how he manipulated the foveated positions to make Pimax (and presumably other canted displays such as index) work? I noted in the logs that there is an indication that there's a radius offset. I'm not sure how it detects, determines this and adapts the other scaling techniques.

**Comment by cedriclmenard** [comment] 2022-01-31 19:18
@DJSlane the issue is that there's currently AFAIK no way to get a single eye's render target view from which Nvidia's VSR does not propagate to both eyes. I'm definitely no expert in DX or Nvidia's VSR, but from my limited research and experiments, I couldn't find one.

Therefore, there's no way to specify a per-eye VSR center. I can get the right values just fine for each eye, but you either get one eye correctly and the other very offset, or the other way around.

The "workaround" was thus to put the VSR center at the image center (not projective center), hence the center not being exactly at the sweet spot of each eye.

I assume this is much worse with high-FOV headset, but unfortunately there's nothing I could find to fix that.

**Comment by DJSlane** [comment] 2022-02-02 23:56
Thanks again. I resolved the issue by trying a larger radius again to essentially allow the periphery that Pimax allows to be rendered as 1/16th. I'm still working on what that radius is, but effectively it may save a few FPS. In my world a few FPS is golden! I really want to say thank you for first pioneering this effort and then investigating what can be done! There's a new OpenXR kit that seems to try to do what you and fholger have done for OpenVR. All I can say is it doesn't look easy. Thanks again for all you've done!

**Comment by DJSlane** [comment] 2022-02-03 01:09
How about the fork from https://github.com/cedriclmenard/vrperfkit

**Comment by DJSlane** [comment] 2022-02-03 01:30
That radius is effectively 0.8 for Pimax. Is there a way that I can use this fork and retain the function of the NIS/CAS/FSR Scaler? I noted above that this fork seems to disble the debug mask and the hotkeys, but it appears to disable the Scaler and Shapening as well - (at least through the hotkeys)?  Also, I was wrong that it didn't affect the FPS much. This was due to the motion smoothing! So now instead of running 60% GPU utilization, I now find 55% GPU utilization for using full resolution with radius 0.8 and 1/16th for the rest. Proof-positive that this can dramatically affect frame rates! WOW!

**Comment by DJSlane** [comment] 2022-02-03 02:48
Also, don't be a fool like me and not realize that @cedriclmenard's vrperfkit.yml quietly has upscaling disabled as default. (I initially thought is was broken). *sigh*

**Comment by fholger** [comment] 2022-03-18 22:04
I added some experimental support for single-eye FFR in vrperfkit 0.3. By default, it counts the number of fitting render targets and then assumes that the first half are for the left eye and the latter for the right. This might or might not be correct for any particular game.

If the foveation patterns do not look correct, you can try and override the order of the eyes in the config file: `overrideSingleEyeOrder`. If debugMode is active, vrperfkit will report in the log file how many render targets it found. For example, if it found 6, the default pattern will be 'LLLRRR' to indicate that the first 3 are assumed to be referring to the left eye, and the final 3 refer to the right eye. You could then try alternative patterns, e.g. 'RRRLLL' to invert the order of the eyes, or perhaps the game is alternating: 'LRLRLR'. Some of the targets may also need to be skipped entirely: 'LLRRSS' or 'LLSRRS' could be worth a try.

**Comment by huliqan** [comment] 2022-03-19 15:54
FFR for 1080ti in v.0.3?

**Comment by fholger** [comment] 2022-03-19 15:56
No, and it is not currently a focus for me, as the alternative method has never really worked well except for 1 or 2 games.

**Comment by Zorinco96** [comment] 2022-03-19 16:03
If someone finds a working foveation pattern for DCS world, please post it!

**Comment by DJSlane** [comment] 2022-03-19 18:33
ok I'll spend some time with it.  Keep in mind the one forked by @cedriclmenard forced central frame FFR and it works sorta well. I mean for high radius FFR it actually pretty good. It won't overlap at the smaller radii, but creates a sort of MasterCard pattern that is close enough to enjoy at higher radii. The reason this works though is because with Non-parallel projection supported games the center of the view is in fact closer to the frame center. So the one from @cedriclmenard works well for Assetto CC, Subnautica 1 and 2, and Dirt Rally 2.0.  It doesn't work well for Elite Dangerous however. (Those bums will never support canted displays).

**Comment by DJSlane** [comment] 2022-03-19 19:03
Doesn't appear to affect DCS. I've treid LRLRLR, RLRLRL, SSSSSS, RLSRLS - always gives the "mastercard overlap". Right eye is slightly to the right Left eye slightly to the left. Perhaps Pimax is submitting the wrong calculations?   They worked correctly in OpenXR so maybe it's their SteamVr data.  They goofed up the Oculus implementation, so it wouldn't surprise me if there's more to the Pimax side.

**Comment by cedriclmenard** [comment] 2022-03-19 20:31
Personally, I’ve just tried the newest version in DCS with an Oculus Quest 2 and it works perfectly with the default pattern, without the "mastercard" FSR pattern.

I assume therefore there is something weird with the Pimax going on. Maybe the projective centers calculations are wrong for the Pimax with DCS?

**Comment by fritzcloud** [comment] 2022-03-19 20:33
Works great out of the box with my reverb g2. Does not work with reshade, but thats fine.

**Comment by Zorinco96** [comment] 2022-03-20 03:00
I wonder if it varies between the different Pimax headsets? When using fholger's v0.3 with an 8KX the FFR would apply only to the right eye, and nothing to the left eye. When I ran the debug mode it showed 46 render targets just on the stock DCS home screen.

**Comment by fholger** [comment] 2022-03-20 14:24
I'll take the feedback as meaning that DCS, in general, works. So I'm closing this issue. Pimax is a separate issue.

**Closed by fholger** 2022-03-20 14:24 UTC

**Comment by akhamar** [comment] 2022-03-20 14:31
I'll have a go with the Varjo Aero and tell you if it does work !

**Comment by akhamar** [comment] 2022-03-20 14:46
Working as intended with Varjo aero. The only downside is that the circles center are too low (bottom) and not align at vertical center.

Is it possible to get on option to offset vertically (and possibly horizontally) the FFR center ?
That would solve the issue of center been too low / too high etc.
